"use strict";

const State = {
  screen: "boot",
  authScreen: "login",
  authUsername: "",
  authPassword: "",
  authFocus: "username",
  authError: "",
  loggedInUser: null,
  sensorMode: "drag",
  desktopSim: false,
  sensorReady: false,
  permissionAsked: false,
  needsCalibration: false,
  holding: null,
  hayLeft: 3,
  feedPlaced: 0,
  eggsCollected: 0,
  petsDone: 0,
  timeLeft: Config.gameSeconds,
  lastTime: 0,
  hoverId: null,
  lastFedId: null,
  toast: "",
  toastTimer: 0,
  resultTitle: "",
  resultBody: "",
  resultGrade: "",
  clearTime: 0,
  collectedEggs: [],
  sessionFriendshipGain: {},
  milestones: {},
  ended: false,
  paused: false,
  shopOverlay: false,
  statusPanel: false,
  pressedButton: null,
  drag: { active: false, moved: false, canPan: false, x: 0, y: 0, yaw: 0, pitch: 0 },
  orientation: { alpha: 0, beta: 0, gamma: 0, has: false },
  calibration: { alpha: 0, beta: 70, gamma: 0 },
  gyroBaseAlpha: 0,
  gyroAccumulatedYaw: 0,
  lastAlpha: null,
  targetLook: { yaw: 0, pitch: 0 },
  look: { yaw: 0, pitch: 0 },
  particles: [],
  floaters: [],
  save: {
    days: 0,
    eggs: 0,
    bestClear: 0,
    perfectDays: 0,
    friendship: {},
    eggQuality: { normal: 0, silver: 0, gold: 0, rare: 0 },
    coins: 0,
    hayStorage: 10,
    heatLamp: false,
    chickenHunger: {},
    users: {},
    currentUser: null,
    ownedChickens: {},
    slots: [],
    currentSlot: 0
  },
  objects: [],
  slots: [],
  currentSlot: 0,
  totalEggsAtStart: 0,
  customMode: { enabled: false, chickens: 3, coins: 0, hay: 10, ownedChickens: {} },
  customEdit: { field: null, value: "" },
  pendingSlotIdx: null
};